# Sistemas Lineares


###Importacoes

In [1]:
import numpy as np

###Sistema triangular superior: substituicao retroativa

In [2]:
def backSubstitution(a, b): #a: matriz principal; b: matriz de termos independentes
  n = len(b)
  for k in range(n-1, -1, -1):
    b[k] = (b[k] - np.dot(a[k, k+1:n], b[k+1:n]))/a[k, k]
  return b

In [3]:
a = np.array([[1.0, 2.0, 1.0,-1.0],
              [0.0,-4.0, 1.0, 7.0],
              [0.0, 0.0,-2.0, 1.0],
              [0.0, 0.0, 0.0,-1.0]])

b = np.array([5.0,1.0,1.0,3.0])

x = np.array([0.0,0.0,0.0,0.0])
n = len(b)

In [4]:
backSubstitution(a,b)

array([16., -6., -2., -3.])

###Sistema triangular inferior: substituicao sucessiva

In [ ]:
a =np.array([[  1  ,   0   , 0],
             [ -0.5,   1   , 0],
             [ 0.25, -0.3  , 1]])

b =np.array([-29, 15, 11])


###Gauss Method

In [ ]:
def gaussElimin(a, b):
    n = len(b)
  # Elimination Phase
    for k in range(0, n-1):
        for i in range(k+1, n):
           if a[i, k] != 0.0:
               lam = a[i, k]/a[k, k]
               a[i, k+1:n] = a[i, k+1:n] - lam*a[k, k+1:n]
               b[i] = b[i] - lam*b[k]
# Back substitution
    backSubstitution(a,b)
    return b

In [ ]:
z = np.array([[-2.0, 3.0, 1.0, 5.0],
              [ 5.0, 1.0,-1.0, 0.0],
              [ 1.0, 6.0, 3.0,-1.0],
              [ 4.0, 5.0, 2.0, 8.0]])

k = np.array([[2.0, -1.0, 0.0, 6.0]])

In [ ]:
gaussElimin(z,k[0])

array([ 0.31421446, -0.81795511,  1.75311721,  0.66583541])

###LU Method


In [ ]:
def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
           if a[i,k] != 0.0:
               lam = a[i,k]/a[k,k]
               a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
               a[i,k] = lam
    return a

In [ ]:
def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
    b[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
       b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [ ]:
z = np.array([[ 3.50, 2.77,-0.76, 1.80],
              [-1.80, 2.68, 3.44,-0.09],
              [ 0.27, 5.07, 6.90, 1.61],
              [ 1.71, 5.45, 2.68, 1.71]])

k = np.array([[7.31, 4.23, 13.85, 11.55]])

In [ ]:
z= LUdecomp(z)
x= LUsolve(z,k[0])

In [ ]:
x

array([1., 1., 1., 1.])

###Exercicio 1.5.2

In [ ]:
def gaussEliminEspec(a, b):
    n = len(b)
    for k in range(0, n-1):
       for i in range(k+1, n):
           if a[i, k] != 0.0:
               lam = a[i, k] / a[k, k]
               a[i, k:n-1] = a[i, k:n-1] - (lam * a[k, k:n-1])
               b[i] = b[i] - lam * b[k]
    for k in range(n-1, -1, -1):
      b[k] = (b[k] - np.dot(a[k, k+1:n], b[k+1:n])) / a[k, k]
    return a

In [ ]:
z = np.array([[-1.0, 3.0, 5.0, 2.0],
              [ 1.0, 9.0, 8.0, 4.0],
              [ 0.0, 1.0, 0.0, 1.0],
              [ 2.0, 1.0, 1.0,-1.0]])

k = np.array([10.0, 15.0, 2.0, -3.0])

In [ ]:
gaussEliminEspec(z,k)

array([[-1.00000000e+00,  3.00000000e+00,  5.00000000e+00,
         2.00000000e+00],
       [ 0.00000000e+00,  1.20000000e+01,  1.30000000e+01,
         4.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.08333333e+00,
         1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16,
        -1.00000000e+00]])

In [ ]:
def f(x):
  return (x** 3) -x -1

In [ ]:
f(1.323)

-0.007314733000000295

Jacobi: com constante de convergência

In [5]:
from numpy.linalg import norm
from numpy import array, zeros, diag, diagflat, dot
from copy import deepcopy
def jacobi(A,b,x):
                                                                                                                                               
    # Criar o vetor da diagonal dos elementos de A
    # Subtraí-los de A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)
    erro = 10**(-2)
    contador = 0
    # Iterando...                                                                                                                                                                        
    while True :
        xa = deepcopy(x)
        x = (b - dot(R,x)) / D
        contador = contador + 1
        print('Iteracao',contador)
        print('Valor do x:',x)
        print('\n')
        if (norm(x-xa))/norm(x) < erro :
                return x,contador

E4 = array([[ 5.0, 1.0, 1.0 ],
            [3.0, 4.0, 1.0 ],
            [ 3.0,3.0, 6.0]])

e4 = array([5.0,6.0,0.0])

ap4 = array([0.0,0.0,0.0])

print(jacobi(E4,e4,ap4))

Iteracao 1
Valor do x: [1.  1.5 0. ]


Iteracao 2
Valor do x: [ 0.7   0.75 -1.25]


Iteracao 3
Valor do x: [ 1.1     1.2875 -0.725 ]


Iteracao 4
Valor do x: [ 0.8875   0.85625 -1.19375]


Iteracao 5
Valor do x: [ 1.0675     1.1328125 -0.871875 ]


Iteracao 6
Valor do x: [ 0.9478125   0.91734375 -1.10015625]


Iteracao 7
Valor do x: [ 1.0365625   1.06417969 -0.93257813]


Iteracao 8
Valor do x: [ 0.97367969  0.95572266 -1.05037109]


Iteracao 9
Valor do x: [ 1.01892969  1.03233301 -0.96470117]


Iteracao 10
Valor do x: [ 0.98647363  0.97697803 -1.02563135]


Iteracao 11
Valor do x: [ 1.00973066  1.01655261 -0.98172583]


Iteracao 12
Valor do x: [ 0.99303464  0.98813346 -1.01314164]


Iteracao 13
Valor do x: [ 1.00500164  1.00850943 -0.99058405]


Iteracao 14
Valor do x: [ 0.99641492  0.99389479 -1.00675553]


Iteracao 15
Valor do x: [ 1.00257215  1.00437769 -0.99515486]


(array([ 1.00257215,  1.00437769, -0.99515486]), 15)


Seidel: Com numero máximo de iterações 

Colocar: 
if (norm(x-xa))/norm(x) < erro :
                return x,contador
caso seja por convergência

In [ ]:
from numpy.linalg import norm
import numpy as np
from copy import deepcopy

def seidel(A, b, x):

    L = np.tril(A)
    U = A - L
    contador = 0
    #erro = 5*10**(-2)
    
    while True:
        xa = deepcopy(x)
        x = np.dot(np.linalg.inv(L), b - np.dot(U, x))
        contador = contador + 1
        print(x, contador)
        if contador == 4:
            return x, contador
 

A = ([[ 4.0, -1.0, 1.0 ],
      [-1.0, 4.0, 2.0 ],
      [ 1.0,-2.0, 4.0]])

b = ([12.0,-1.0,5.0])

x = ([0.0,0.0,0.0])

print(seidel(A,b,x))